Public Class FrmCOA
#Region "Declaration"
    Dim coaID As Integer = 0
    Dim display As String = ""
    Dim isCreate As Boolean = False
    Dim isUpdate As Boolean = False
    Dim isDelete As Boolean = False
    Dim coaName As String
#End Region
#Region "Function"
    Sub CheckPermissions()
        Dim roleBFC As ClsPermission = New ClsPermission
        Dim roleModel As RoleDModel = New RoleDModel
        roleModel = roleBFC.RetrieveDetailsByRoleIDMenuID(roleIDUser, Tag)
        If roleModel.IsCreate = True Then isCreate = True
        If roleModel.IsUpdate = True Then isUpdate = True
        If roleModel.IsDelete = True Then isDelete = True
    End Sub
    Sub ClearText()
        txtCode.Text = AutoGenerated
        txtName.Clear()
        coaName = ""
        cmbCost.Text = ""
        cmbCari.Text = ""
        txtCari.Clear()
    End Sub
    Sub PropertiesGrid()
        With dgv
            .Columns(0).Visible = False
            .Columns(1).HeaderText = "COA Code"
            .Columns(1).Width = 200
            .Columns(2).HeaderText = "COA Name"
            .Columns(2).Width = 200
            .Columns(3).HeaderText = "Cost Center"
            .Columns(3).Width = 200
            .Columns(4).Visible = False
        End With
    End Sub
    Sub ListCOA(myOptions As String, myParam As String)
        Try
            Dim coaBFC As ClsCOA = New ClsCOA
            dgv.DataSource = coaBFC.RetrieveList(myOptions, myParam)
            dgv.ReadOnly = True
            PropertiesGrid()
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Function CheckEmpty() As Boolean
        Dim check As Boolean = True
        If Trim(txtName.Text) = String.Empty Then
            MsgBoxWarning("Name can't empty")
            txtName.Focus()
        ElseIf Trim(cmbCost.Text) = "" Then
            MsgBoxWarning("Cost Center can't empty")
            txtName.Focus()
        Else
            check = False
        End If
        Return check
    End Function
    Function SetModel() As COAModel
        Dim coaModel As COAModel = New COAModel
        Dim coaBFC As ClsCOA = New ClsCOA
        With coaModel
            Select Case display
                Case "Create"
                    .CoaID = coaBFC.GeneratedAutoNumber
                    .CoaCode = coaBFC.GeneratedCode
                    .CoaName = txtName.Text
                    .CostCenter = cmbCost.Text
                    .IsActive = True
                    .CreatedBy = userID
                    .CreatedDate = DateTime.Now
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                Case "Update"
                    .CoaID = coaID
                    .CoaName = txtName.Text
                    .CostCenter = cmbCost.Text
                    .IsActive = True
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                Case Else
                    .CoaID = coaID
                    .IsActive = False
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
            End Select
        End With
        Return coaModel
    End Function
    Sub EnabledText(status As Boolean)
        txtName.Enabled = status
        cmbCost.Enabled = status
    End Sub
    Sub ButtonAdd()
        If isCreate = True Then btnAdd.Enabled = True
        btnSave.Enabled = False
        btnDelete.Enabled = False
        btnCancel.Enabled = False
    End Sub
    Sub ButtonSave()
        btnAdd.Enabled = False
        btnSave.Enabled = True
        btnDelete.Enabled = False
        btnCancel.Enabled = True
    End Sub
    Sub ButtonUpdate()
        btnAdd.Enabled = False
        If isUpdate = True Then btnSave.Enabled = True
        If isDelete = True Then btnDelete.Enabled = True
        btnCancel.Enabled = True
    End Sub
    Sub PreCreateDisplay()
        CheckPermissions()
        ClearText()
        ListCOA(cmbCari.Text, txtCari.Text)
        EnabledText(False)
        ButtonAdd()
        display = ""
        Text = title
    End Sub
    Sub InsertCOA()
        Dim coaBFC As ClsCOA = New ClsCOA
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Create new COA,COA name is " + txtName.Text
        Try
            If coaBFC.GetValidateName(txtName.Text) Then
                If coaBFC.InsertCOA(SetModel, logBFC.SetLogHistory(logDesc)) = True Then
                    MsgBoxSaved()
                    PreCreateDisplay()
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub UpdateCOA()
        Dim coaBFC As ClsCOA = New ClsCOA
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update COA for Code = " + txtCode.Text
        Try
            If txtName.Text = coaName Then
                If coaBFC.UpdateCOA(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                    MsgBoxUpdated()
                    PreCreateDisplay()
                End If
            ElseIf txtName.Text <> coaName Then
                If coaBFC.GetValidateName(txtName.Text) Then
                    If coaBFC.UpdateCOA(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                        MsgBoxUpdated()
                        PreCreateDisplay()
                    End If
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub DeleteCOA()
        Dim coaBFC As ClsCOA = New ClsCOA
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update COA for Code = " + txtCode.Text + ",update IsActive = False"
        display = "Delete"
        Try
            If coaBFC.UpdateCOA(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                MsgBoxDeleted()
                PreCreateDisplay()
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
#End Region
#Region "Button"
    Private Sub btnAdd_Click(sender As Object, e As EventArgs) Handles btnAdd.Click
        EnabledText(True)
        display = "Create"
        ButtonSave()
        txtName.Focus()
    End Sub

    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        If CheckEmpty() = False Then
            Try
                Select Case display
                    Case "Create"
                        InsertCOA()
                    Case "Update"
                        UpdateCOA()
                End Select
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnDelete_Click(sender As Object, e As EventArgs) Handles btnDelete.Click
        If MsgBoxQuestion() = DialogResult.Yes Then
            Try
                DeleteCOA()
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        PreCreateDisplay()
    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnExit.Click
        Close()
    End Sub
#End Region
#Region "Other"
    Private Sub txtName_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtName.KeyPress
        If e.KeyChar = Chr(13) Then
            cmbCost.Focus()
        End If
    End Sub

    Private Sub cmbCost_KeyPress(sender As Object, e As KeyPressEventArgs) Handles cmbCost.KeyPress
        e.KeyChar = Chr(0)
    End Sub

    Private Sub cmbCost_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cmbCost.SelectedIndexChanged
        btnSave.Focus()
    End Sub

    Private Sub cmbCari_KeyPress(sender As Object, e As KeyPressEventArgs) Handles cmbCari.KeyPress
        e.KeyChar = Chr(0)
    End Sub

    Private Sub cmbCari_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cmbCari.SelectedIndexChanged
        txtCari.Focus()
    End Sub

    Private Sub txtCari_TextChanged(sender As Object, e As EventArgs) Handles txtCari.TextChanged
        ListCOA(cmbCari.Text, txtCari.Text)
    End Sub

    Private Sub dgv_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgv.CellClick
        With dgv
            If .RowCount > 1 Then
                Dim row As Integer = .CurrentRow.Index
                coaID = .Item(0, row).Value
                txtCode.Text = .Item(1, row).Value
                txtName.Text = .Item(2, row).Value
                coaName = txtName.Text
                cmbCost.Text = .Item(3, row).Value
                display = "Update"

                ButtonUpdate()
                EnabledText(True)
            End If
        End With
    End Sub

    Private Sub FrmCOA_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PreCreateDisplay()
    End Sub
#End Region



End Class