Public Class FrmSeason
#Region "Declaration"
    Dim seasonID As Integer = 0
    Dim display As String = ""
    Dim isCreate As Boolean = False
    Dim isUpdate As Boolean = False
    Dim isDelete As Boolean = False
    Dim seasonName As String = ""
#End Region
#Region "Function"
    Sub CheckPermissions()
        Dim roleBFC As ClsPermission = New ClsPermission
        Dim roleModel As RoleDModel = New RoleDModel
        roleModel = roleBFC.RetrieveDetailsByRoleIDMenuID(roleIDUser, Tag)
        If roleModel.IsCreate = True Then isCreate = True
        If roleModel.IsUpdate = True Then isUpdate = True
        If roleModel.IsDelete = True Then isDelete = True
    End Sub
    Sub ClearText()
        txtCode.Text = AutoGenerated
        txtName.Clear()
        txtDesc.Clear()
        cmbCari.Text = ""
        txtCari.Clear()
        seasonName = ""
    End Sub
    Sub PropertiesGrid()
        With dgv
            .Columns(0).Visible = False
            .Columns(1).HeaderText = "Season Code"
            .Columns(1).Width = 200
            .Columns(2).HeaderText = "Season Name"
            .Columns(2).Width = 200
            .Columns(3).HeaderText = "Description"
            .Columns(3).Width = 200
            .Columns(4).HeaderText = "Customer"
            .Columns(4).Width = 200

            .Columns(5).Visible = False
            .Columns(6).Visible = False
        End With
    End Sub
    Sub ListSeason(myOptions As String, myParam As String)
        Try
            Dim seasonBFC As ClsSeason = New ClsSeason
            dgv.DataSource = seasonBFC.RetrieveList(myOptions, myParam)
            dgv.ReadOnly = True
            PropertiesGrid()
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub ComboBoxCustomer(cmb As ComboBox)
        Dim vendorBFC As ClsVendor = New ClsVendor
        Dim statusVendor As Char = "C"
        vendorBFC.ComboBoxVendor(cmb, statusVendor)
    End Sub
    Function CheckEmpty() As Boolean
        Dim check As Boolean = True
        If Trim(txtName.Text) = String.Empty Then
            MsgBoxWarning("Name can't empty")
            txtName.Focus()
        ElseIf Trim(txtDesc.Text) = String.Empty Then
            MsgBoxWarning("Description can't empty")
            txtDesc.Focus()
        Else
            check = False
        End If
        Return check
    End Function
    Function SetModel() As SeasonModel
        Dim seasonModel As SeasonModel = New SeasonModel
        Dim seasonBFC As ClsSeason = New ClsSeason
        With seasonModel
            Select Case display
                Case "Create"
                    .SeasonID = seasonBFC.GeneratedAutoNumber
                    .SeasonCode = seasonBFC.GeneratedCode
                    .SeasonName = txtName.Text
                    .Description = txtDesc.Text
                    .VendorID = cmbVendor.SelectedValue
                    .IsActive = True
                    .CreatedBy = userID
                    .CreatedDate = DateTime.Now
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                Case "Update"
                    .SeasonID = seasonID
                    .SeasonName = txtName.Text
                    .Description = txtDesc.Text
                    .VendorID = cmbVendor.SelectedValue
                    .IsActive = True
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                Case Else
                    .SeasonID = seasonID
                    .IsActive = False
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
            End Select
        End With
        Return seasonModel
    End Function
    Sub EnabledText(status As Boolean)
        txtName.Enabled = status
        txtDesc.Enabled = status
        cmbVendor.Enabled = status
    End Sub
    Sub ButtonAdd()
        If isCreate = True Then btnAdd.Enabled = True
        btnSave.Enabled = False
        btnDelete.Enabled = False
        btnCancel.Enabled = False
    End Sub
    Sub ButtonSave()
        btnAdd.Enabled = False
        btnSave.Enabled = True
        btnDelete.Enabled = False
        btnCancel.Enabled = True
    End Sub
    Sub ButtonUpdate()
        btnAdd.Enabled = False
        If isUpdate = True Then btnSave.Enabled = True
        If isDelete = True Then btnDelete.Enabled = True
        btnCancel.Enabled = True
    End Sub
    Sub PreCreateDisplay()
        CheckPermissions()
        ClearText()
        ListSeason(cmbCari.Text, txtCari.Text)
        ComboBoxCustomer(cmbVendor)
        EnabledText(False)
        ButtonAdd()
        display = ""
        Text = title
    End Sub
    Sub InsertSeason()
        Dim seasonBFC As ClsSeason = New ClsSeason
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Create new Season,Season name is " + txtName.Text
        Try
            If seasonBFC.GetValidateName(txtName.Text) = True Then
                If seasonBFC.InsertSeason(SetModel, logBFC.SetLogHistory(logDesc)) = True Then
                    MsgBoxSaved()
                    PreCreateDisplay()
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub UpdateSeason()
        Dim seasonBFC As ClsSeason = New ClsSeason
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update Season for Code = " + txtCode.Text
        Try
            If txtName.Text = seasonName Then
                If seasonBFC.UpdateSeason(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                    MsgBoxUpdated()
                    PreCreateDisplay()
                End If
            ElseIf txtName.Text <> seasonName Then
                If seasonBFC.GetValidateName(txtName.Text) = True Then
                    If seasonBFC.UpdateSeason(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                        MsgBoxUpdated()
                        PreCreateDisplay()
                    End If
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub DeleteSeason()
        Dim seasonBFC As ClsSeason = New ClsSeason
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update Season for Code = " + txtCode.Text + ",update IsActive = False"
        display = "Delete"
        Try
            If seasonBFC.UpdateSeason(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                MsgBoxDeleted()
                PreCreateDisplay()
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
#End Region

#Region "Button"
    Private Sub btnAdd_Click(sender As Object, e As EventArgs) Handles btnAdd.Click
        EnabledText(True)
        display = "Create"
        ButtonSave()
        txtName.Focus()
    End Sub

    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        If CheckEmpty() = False Then
            Try
                Select Case display
                    Case "Create"
                        InsertSeason()
                    Case "Update"
                        UpdateSeason()
                End Select
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnDelete_Click(sender As Object, e As EventArgs) Handles btnDelete.Click
        If MsgBoxQuestion() = DialogResult.Yes Then
            Try
                DeleteSeason()
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        PreCreateDisplay()
    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnExit.Click
        Close()
    End Sub
#End Region

#Region "Other"
    Private Sub txtName_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtName.KeyPress
        If e.KeyChar = Chr(13) Then
            txtDesc.Focus()
        End If
    End Sub

    Private Sub txtDesc_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtDesc.KeyPress
        If e.KeyChar = Chr(13) Then
            cmbVendor.Focus()
        End If
    End Sub

    Private Sub cmbVendor_KeyPress(sender As Object, e As KeyPressEventArgs) Handles cmbVendor.KeyPress
        e.KeyChar = Chr(0)
    End Sub

    Private Sub cmbVendor_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cmbVendor.SelectedIndexChanged
        btnSave.Focus()
    End Sub

    Private Sub cmbCari_KeyPress(sender As Object, e As KeyPressEventArgs) Handles cmbCari.KeyPress
        e.KeyChar = Chr(0)
    End Sub

    Private Sub cmbCari_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cmbCari.SelectedIndexChanged
        txtCari.Focus()
    End Sub

    Private Sub txtCari_TextChanged(sender As Object, e As EventArgs) Handles txtCari.TextChanged
        ListSeason(cmbCari.Text, txtCari.Text)
    End Sub

    Private Sub dgv_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgv.CellClick
        ComboBoxCustomer(cmbVendor)
        With dgv
            If .RowCount > 1 Then
                Dim row As Integer = .CurrentRow.Index
                seasonID = .Item(0, row).Value
                txtCode.Text = .Item(1, row).Value
                txtName.Text = .Item(2, row).Value
                txtDesc.Text = .Item(3, row).Value
                cmbVendor.SelectedValue = .Item(5, row).Value
                display = "Update"

                ButtonUpdate()
                EnabledText(True)
            End If
        End With
    End Sub

    Private Sub FrmSeason_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PreCreateDisplay()
    End Sub
#End Region
End Class