Public Class FrmTermOfPayment
#Region "Declaration"
    Dim termID As Integer = 0
    Dim topName As String
    Dim display As String = ""
    Dim isCreate As Boolean = False
    Dim isUpdate As Boolean = False
    Dim isDelete As Boolean = False
#End Region

#Region "Function"
    Sub ClearText()
        txtCode.Text = AutoGenerated
        txtName.Clear()
        txtDesc.Clear()
        cmbCari.Text = ""
        txtCari.Clear()
    End Sub
    Sub PropertiesGrid()
        With dgv
            .Columns(0).Visible = False
            .Columns(1).HeaderText = "TermOfPayment Code"
            .Columns(1).Width = 200
            .Columns(2).HeaderText = "Name"
            .Columns(2).Width = 200
            .Columns(3).HeaderText = "Description"
            .Columns(3).Width = 200
            .Columns(4).Visible = False
            .Columns(5).Visible = False
            .Columns(6).Visible = False
            .Columns(7).Visible = False
            .Columns(8).Visible = False
        End With
    End Sub
    Sub ListTerm(myOptions As String, myParam As String)
        Try
            Dim termBFC As ClsTermOfPayment = New ClsTermOfPayment
            With dgv
                .DataSource = termBFC.RetrieveList(myOptions, myParam)
                .ReadOnly = True
            End With
            PropertiesGrid()
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
    Sub EnabledText(status As Boolean)
        txtName.Enabled = status
        txtDesc.Enabled = status
    End Sub
    Sub CheckPermissions()
        Dim roleBFC As ClsPermission = New ClsPermission
        Dim roleModel As RoleDModel = New RoleDModel
        roleModel = roleBFC.RetrieveDetailsByRoleIDMenuID(roleIDUser, Tag)
        If roleModel.IsCreate = True Then isCreate = True
        If roleModel.IsUpdate = True Then isUpdate = True
        If roleModel.IsDelete = True Then isDelete = True
    End Sub
    Sub ButtonAdd()
        If isCreate = True Then btnAdd.Enabled = True
        btnSave.Enabled = False
        btnDelete.Enabled = False
        btnCancel.Enabled = False
    End Sub
    Sub ButtonSave()
        btnAdd.Enabled = False
        btnSave.Enabled = True
        btnDelete.Enabled = False
        btnCancel.Enabled = True
    End Sub
    Sub ButtonUpdate()
        btnAdd.Enabled = False
        If isUpdate = True Then btnSave.Enabled = True
        If isDelete = True Then btnDelete.Enabled = True
        btnCancel.Enabled = True
    End Sub
    Sub PreCreateDisplay()
        CheckPermissions()
        ClearText()
        ListTerm(cmbCari.Text, txtCari.Text)
        EnabledText(False)
        ButtonAdd()
        display = ""
        btnAdd.Focus()
        Text = title
    End Sub
    Function CheckEmpty() As Boolean
        Dim check As Boolean = True
        If Trim(txtName.Text) = String.Empty Then
            MsgBoxWarning("Name can't empty")
            txtName.Focus()
        ElseIf Trim(txtDesc.Text) = String.Empty Then
            MsgBoxWarning("Description can't empty")
            txtDesc.Focus()
        Else
            check = False
        End If
        Return check
    End Function
    Function SetModel() As TermOfPaymentModel
        Dim termModel As TermOfPaymentModel = New TermOfPaymentModel
        Dim termBFC As ClsTermOfPayment = New ClsTermOfPayment
        Select Case display
            Case "Create"
                With termModel
                    .TermOfPaymentID = termBFC.GeneratedAutoNumber
                    .TermOfPaymentCode = termBFC.GeneratedCode
                    .Name = txtName.Text
                    .Description = txtDesc.Text
                    .IsActive = True
                    .CreatedBy = userID
                    .CreatedDate = DateTime.Now
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                End With
            Case "Update"
                With termModel
                    .TermOfPaymentID = termID
                    .Name = txtName.Text
                    .Description = txtDesc.Text
                    .IsActive = True
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                End With
            Case Else
                With termModel
                    .TermOfPaymentID = termID
                    .IsActive = False
                    .UpdatedBy = userID
                    .UpdatedDate = DateTime.Now
                End With
        End Select
        Return termModel
    End Function
    Sub InsertTerm()
        Dim termBFC As ClsTermOfPayment = New ClsTermOfPayment
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Create new Term Of Payment,Term Of Payment name is " + txtName.Text
        Try
            If termBFC.GetValidateName(txtName.Text) Then
                If termBFC.InsertTerm(SetModel, logBFC.SetLogHistory(logDesc)) = True Then
                    MsgBoxSaved()
                    PreCreateDisplay()
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub

    Sub UpdateTerm()
        Dim termBFC As ClsTermOfPayment = New ClsTermOfPayment
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update Term Of Payment for TermOfPaymentCode = " + txtCode.Text
        Try
            If txtName.Text = topName Then
                If termBFC.UpdateTerm(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                    MsgBoxUpdated()
                    PreCreateDisplay()
                End If
            ElseIf txtName.Text <> topName Then
                If termBFC.GetValidateName(txtName.Text) Then
                    If termBFC.UpdateTerm(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                        MsgBoxUpdated()
                        PreCreateDisplay()
                    End If
                End If
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub

    Sub DeleteTerm()
        Dim termBFC As ClsTermOfPayment = New ClsTermOfPayment
        Dim logBFC As ClsLogHistory = New ClsLogHistory
        Dim logDesc As String = "Update Term Of Payment for TermOfPaymentCode = " + txtCode.Text + ",update IsActive = False"
        display = "Delete"
        Try
            If termBFC.UpdateTerm(SetModel, logBFC.SetLogHistory(logDesc), display) = True Then
                MsgBoxDeleted()
                PreCreateDisplay()
            End If
        Catch ex As Exception
            MsgBoxError(ex.Message)
        End Try
    End Sub
#End Region

#Region "Button"
    Private Sub btnAdd_Click(sender As Object, e As EventArgs) Handles btnAdd.Click
        EnabledText(True)
        display = "Create"
        ButtonSave()
        txtName.Focus()
    End Sub

    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        If CheckEmpty() = False Then
            Try
                Select Case display
                    Case "Create"
                        InsertTerm()
                    Case "Update"
                        UpdateTerm()
                End Select
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnDelete_Click(sender As Object, e As EventArgs) Handles btnDelete.Click
        If MsgBoxQuestion() = DialogResult.Yes Then
            Try
                DeleteTerm()
            Catch ex As Exception
                MsgBoxError(ex.Message)
            End Try
        End If
    End Sub

    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        PreCreateDisplay()
    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnExit.Click
        Close()
    End Sub
#End Region

#Region "Other"
    Private Sub FrmTermOfPayment_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PreCreateDisplay()
        txtName.Focus()
    End Sub

    Private Sub txtName_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtName.KeyPress
        If e.KeyChar = Chr(13) Then
            txtDesc.Focus()
        End If
    End Sub

    Private Sub txtDesc_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtDesc.KeyPress
        If e.KeyChar = Chr(13) Then
            btnSave.Focus()
        End If
    End Sub

    Private Sub cmbCari_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cmbCari.SelectedIndexChanged
        txtCari.Focus()
    End Sub

    Private Sub cmbCari_KeyPress(sender As Object, e As KeyPressEventArgs) Handles cmbCari.KeyPress
        e.KeyChar = Chr(0)
    End Sub

    Private Sub txtCari_TextChanged(sender As Object, e As EventArgs) Handles txtCari.TextChanged
        ListTerm(cmbCari.Text, txtCari.Text)
    End Sub
    Private Sub dgv_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgv.CellClick
        With dgv
            Dim row As Integer = .CurrentRow.Index
            termID = .Item(0, row).Value
            txtCode.Text = .Item(1, row).Value
            txtName.Text = .Item(2, row).Value
            topName = txtName.Text
            txtDesc.Text = .Item(3, row).Value
        End With

        display = "Update"

        ButtonUpdate()
        EnabledText(True)
    End Sub
#End Region
End Class