Imports System.Text.RegularExpressions

Module MdlHelper
    Public userID As Integer = 0
    Public userName As String = ""
    Public stringIPUser As String = ""
    Public roleIDUser As Integer = 0

    Public valueKey As String = "This a Key"
    Public title As String = "PT.Ocean Asia Industri"
    Public Const AutoGenerated As String = "Auto Generated"
    Public Sub MsgBoxInformation(ByVal msg As String)
        MsgBox(msg, MsgBoxStyle.Information, title)
    End Sub
    Public Sub MsgBoxError(ByVal msg As String)
        MsgBox(msg, MsgBoxStyle.Critical, title)
    End Sub
    Public Sub MsgBoxWarning(msg As String)
        MsgBox(msg, MsgBoxStyle.Exclamation, title)
    End Sub
    Public Sub MsgBoxSaved()
        MsgBoxInformation("Data has been saved")
    End Sub
    Public Sub MsgBoxUpdated()
        MsgBoxInformation("Data has been updated")
    End Sub
    Public Sub MsgBoxApproved()
        MsgBoxInformation("Data has been Approved")
    End Sub
    Public Sub MsgBoxVoid()
        MsgBoxInformation("Data has been Voided")
    End Sub
    Public Sub MsgBoxDeleted()
        MsgBoxInformation("Data has been deleted")
    End Sub
    Public Function MsgBoxQuestion() As DialogResult
        Dim result2 As DialogResult = MessageBox.Show("Are you sure data will be deleted?", title, MessageBoxButtons.YesNo, MessageBoxIcon.Question)
        Return result2
    End Function
    Public Function MsgBoxQuestionExit() As DialogResult
        Dim result As DialogResult = MessageBox.Show("Are you sure want to exit application?", title, MessageBoxButtons.YesNo, MessageBoxIcon.Question)
        Return result
    End Function
    Public Function ValidationNumber(txt As TextBox) As Boolean
        If Not IsNumeric(txt.Text) Then
            Return False
        Else
            Return True
        End If
    End Function
    Public Sub CheckNumber(txt As TextBox)
        If txt.Text = String.Empty Then
            txt.Text = ""
        Else
            If ValidationNumber(txt) = False Then
                txt.Text = 0
                txt.Focus()
            End If
        End If
    End Sub
    Public Sub DeleteGrid(dgv As DataGridView, baris As Integer)
        dgv.Rows.RemoveAt(dgv.CurrentCell.RowIndex)
        baris = baris - 1
    End Sub
    Public Function ValidationEmail(value As String) As Boolean
        Dim pattern As String = "^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$"
        If Regex.Match(value, pattern).Success Then
            Return True
        Else
            Return False
        End If
    End Function
End Module
